Repository galaxybomb23/ECE461-Software-Engineering, pull requests merged in 2024-09, with the labels that each got.

#14 Correctness Is Done WOOOH!
  package-lock.json
  package.json
  run
  src/cli.ts
  test/URLS.txt
  tsconfig.json
Labels: enhancement

#19 Correctness done again ooh
  run
  src/cli.ts
Labels: enhancement

#32 Added testing to maintainability and fixed typo in metrics.ts
  src/Metrics.ts
  src/cli.ts
  src/maintainability.ts
Labels: enhancement, good first issue

#34 Added getRepoData to parent class metrics
  src/Metrics.ts
  src/busFactor.ts
  src/correctness.ts
  src/maintainability.ts
  src/rampUp.ts
Labels: enhancement

#36 22 code optimization
  src/Metrics.ts
  src/busFactor.ts
  src/cli.ts
  src/correctness.ts
  src/license.ts
  src/maintainability.ts
  src/netScore.ts
  src/rampUp.ts
  src/testUtils.ts
Labels: documentation, enhancement

#42 35-logging :: Added Logging functionality to project
  .github/workflows/ci.yaml
  .gitignore
  package-lock.json
  package.json
  run
  src/Metrics.ts
  src/busFactor.ts
  src/cli.ts
  src/correctness.ts
  src/license.ts
  src/maintainability.ts
  src/netScore.ts
  src/rampUp.ts
  src/testUtils.ts
Labels: enhancement

#49 Create .env
  .env
Labels: documentation, enhancement

#51 deleted .env
  .env
Labels: bug

#53 added some logging
  checker/checker.py
  run
  src/Metrics.ts
  src/busFactor.ts
  src/cli.ts
  src/correctness.ts
  src/license.ts
  src/maintainability.ts
  src/netScore.ts
  src/rampUp.ts
Labels: bug, enhancement

#55 43 handoff docs
  README.md
  src/Metrics.ts
  src/busFactor.ts
  src/cli.ts
  src/correctness.ts
  src/license.ts
  src/maintainability.ts
  src/netScore.ts
  src/rampUp.ts
Labels: documentation

#56 Update README.md to include purpose
  README.md
Labels: enhancement
